disable_existing_loggers: false
formatters:
    standard:
        datefmt: '%Y-%m-%d %H:%M:%S'
        format: '%(asctime)s  [%(name)-8.8s]  [%(levelname)-6.6s]  :::  %(message)s'
    console:
        format: '%(message)s'
handlers:
    console:
        class: logging.StreamHandler
        formatter: standard
        level: DEBUG
    file:
        level: DEBUG
        class: logging.handlers.TimedRotatingFileHandler
        formatter: standard
        filename: logs/process.log
        when: midnight
        backupCount: 10
loggers:
    "":
        handlers:
            - console
            - file
        level: DEBUG
        propagate: true
    "urllib3":
        level: INFO
        propagate: true
version: 1
